import os
import pandas as pd
import requests
from dotenv import load_dotenv
from time import sleep


# Load API key and data
load_dotenv()
API_KEY = os.getenv("OPENWEATHER_API_KEY")
if not API_KEY:
    raise ValueError(" Missing OpenWeatherMap API key ")

INPUT_FILE = "pollution_data.csv"
OUTPUT_FILE = "weather_data.csv"

# Load pollution data (generated by openaq_fetch.py)
if not os.path.exists(INPUT_FILE):
    raise FileNotFoundError(f" {INPUT_FILE} not found. Run openaq_fetch.py first.")

pollution_df = pd.read_csv(INPUT_FILE)
coords = pollution_df[['latitude', 'longitude']].drop_duplicates()

print(f" Found {len(coords)} unique locations to fetch weather data for.\n")


# Define Weather Fetch Function
def get_weather(lat, lon):
    url = "https://api.openweathermap.org/data/2.5/weather"
    params = {
        "lat": lat,
        "lon": lon,
        "appid": API_KEY,
        "units": "metric"
    }
    try:
        r = requests.get(url, params=params)
        r.raise_for_status()
        data = r.json()
        return {
            "latitude": lat,
            "longitude": lon,
            "temperature": data["main"]["temp"],
            "humidity": data["main"]["humidity"],
            "pressure": data["main"]["pressure"],
            "wind_speed": data["wind"]["speed"],
            "wind_deg": data["wind"].get("deg"),
            "weather": data["weather"][0]["description"]
        }
    except Exception as e:
        print(f" Failed for ({lat}, {lon}): {e}")
        return None


# Fetch Weather for Each Unique Location

records = []
for _, row in coords.iterrows():
    lat, lon = row['latitude'], row['longitude']
    weather = get_weather(lat, lon)
    if weather:
        records.append(weather)
    sleep(1)  # be polite to API

weather_df = pd.DataFrame(records)
weather_df.to_csv(OUTPUT_FILE, index=False)

print(f" Weather data saved → {OUTPUT_FILE} ({len(weather_df)} records)")
print("\nPreview:")
print(weather_df.head())
